# Generated by Django 4.1.1 on 2023-10-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_prenda", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("talla", models.CharField(max_length=100)),
                ("detalle", models.CharField(max_length=100)),
                ("img", models.ImageField(blank="True", upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idU", models.IntegerField()),
                ("nombre", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254)),
            ],
        ),
    ]
